"""add category column

Revision ID: e1c434e75870
Revises: 007d2f2565dd
Create Date: 2025-04-01 17:03:47.361975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c434e75870'
down_revision: Union[str, None] = '007d2f2565dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###
